name: Module Builder

on:
    push:
        branches:
            - main

jobs:
    debug:
      name: Debug
      runs-on: ubuntu-latest
      steps:
        - name: Dump env
          run: env | sort
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"  
    build:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - uses: actions/checkout@v4

            - name: Zip Files
              working-directory: ./
              run: zip -r ./module.zip ./*

            - name: Get Version
              shell: bash
              id: get-version
              run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

            - name: Create Release
              id: create-release
              uses: ncipollo/release-action@v1
              with: 
                allowUpdates: true
                name: Release ${{ steps.get-version.outputs.version }}
                draft: false
                prerelease: false
                token: ${{ secrets.GITHUB_TOKEN }} 
                artifacts: './module.zip, ./module.json'
                tag: v${{ steps.get-version.outputs.version }}

            - name: Publish Module to FoundryVTT Website
              id: publish-to-foundry-website
              uses: cs96and/FoundryVTT-release-package@v1
              with:
                package-token: ${{ secrets.FOUNDRY_TOKEN }}
                manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json